"use client";

import {useEffect,useState} from "react";
import {CheckCircle2,KeyRound,ShieldAlert} from "lucide-react";
import {Button} from "@/components/ui/button";
import {Input} from "@/components/ui/input";
import {getSupabase,isLocalDemo} from "@/lib/supabase";

export default function SetupPasswordPage(){
 const supabase=getSupabase();
 const [checking,setChecking]=useState(true),[valid,setValid]=useState(false),[password,setPassword]=useState(""),[confirm,setConfirm]=useState(""),[error,setError]=useState(""),[saving,setSaving]=useState(false),[done,setDone]=useState(false);
 useEffect(()=>{let mounted=true;if(isLocalDemo()){setError("Chế độ cục bộ không cần kích hoạt tài khoản.");setChecking(false);return}async function check(){const hash=new URLSearchParams(window.location.hash.slice(1)),authError=hash.get("error_description");if(authError){if(mounted){setError(hash.get("error_code")==="otp_expired"?"Link mời đã hết hạn hoặc đã được sử dụng. Vui lòng đề nghị quản trị viên gửi lại lời mời mới.":decodeURIComponent(authError.replace(/\+/g," ")));setChecking(false)}return}const {data}=await supabase.auth.getSession();if(mounted){setValid(Boolean(data.session));setError(data.session?"":"Không tìm thấy phiên kích hoạt hợp lệ. Vui lòng mở lại email mời mới nhất.");setChecking(false)}}void check();const {data:{subscription}}=supabase.auth.onAuthStateChange((_event:string,session:any)=>{if(mounted&&session){setValid(true);setError("");setChecking(false)}});return()=>{mounted=false;subscription.unsubscribe()}},[supabase]);
 async function submit(e:React.FormEvent){e.preventDefault();setError("");if(password.length<8){setError("Mật khẩu phải có ít nhất 8 ký tự.");return}if(password!==confirm){setError("Hai mật khẩu chưa trùng khớp.");return}setSaving(true);const {error:updateError}=await supabase.auth.updateUser({password});setSaving(false);if(updateError){setError(updateError.message);return}setDone(true);window.history.replaceState(null,"",window.location.pathname);setTimeout(()=>window.location.replace("/"),1200)}
 return <main className="grid min-h-screen place-items-center bg-[#eef4f1] p-5"><section className="w-full max-w-md rounded-2xl border border-[#dce7e1] bg-white p-7 shadow-sm">{done?<div className="py-8 text-center"><CheckCircle2 className="mx-auto text-emerald-600" size={48}/><h1 className="mt-4 text-2xl font-bold">Đã tạo mật khẩu</h1><p className="mt-2 text-sm text-slate-600">Đang chuyển vào hệ thống...</p></div>:<><span className="grid h-12 w-12 place-items-center rounded-xl bg-[#0a6849] text-white">{error&&!valid?<ShieldAlert/>:<KeyRound/>}</span><h1 className="mt-5 text-2xl font-bold">Tạo mật khẩu tài khoản</h1><p className="mt-2 text-sm leading-6 text-slate-600">Hoàn tất lời mời Supabase để sử dụng hệ thống vệ sinh nhà máy.</p>{checking?<p className="mt-6 rounded-xl bg-slate-50 p-4 text-sm">Đang kiểm tra link mời...</p>:valid?<form onSubmit={submit} className="mt-6 space-y-4"><label className="block text-sm font-semibold">Mật khẩu mới<Input className="mt-2" type="password" minLength={8} required autoComplete="new-password" value={password} onChange={e=>setPassword(e.target.value)} placeholder="Tối thiểu 8 ký tự"/></label><label className="block text-sm font-semibold">Nhập lại mật khẩu<Input className="mt-2" type="password" minLength={8} required autoComplete="new-password" value={confirm} onChange={e=>setConfirm(e.target.value)} placeholder="Nhập lại mật khẩu"/></label>{error&&<p className="rounded-xl bg-rose-50 p-3 text-sm text-rose-700">{error}</p>}<Button disabled={saving} className="w-full bg-[#0a6849]">{saving?"Đang lưu...":"Tạo mật khẩu và đăng nhập"}</Button></form>:<div className="mt-6"><p className="rounded-xl bg-rose-50 p-4 text-sm leading-6 text-rose-700">{error}</p><Button variant="outline" className="mt-4 w-full" onClick={()=>window.location.replace("/")}>Về trang đăng nhập</Button></div>}</>}</section></main>
}
