"use client";
import {useEffect,useMemo,useState} from "react";
import {AlertTriangle,Beaker,CalendarDays,Check,ClipboardCheck,FileText,FlaskConical,LayoutDashboard,Menu,Plus,RefreshCw,Search,ShieldCheck,Sparkles,X} from "lucide-react";
import {Badge} from "@/components/ui/badge"; import {Button} from "@/components/ui/button";
import {Dialog,DialogContent,DialogDescription,DialogFooter,DialogHeader,DialogTitle,DialogTrigger} from "@/components/ui/dialog";
import {Input} from "@/components/ui/input"; import {Label} from "@/components/ui/label"; import {NativeSelect,NativeSelectOption} from "@/components/ui/native-select";
import {Tabs,TabsContent,TabsList,TabsTrigger} from "@/components/ui/tabs";
type Rec={id:number;area:string;line:string;chemical:string;cleanedAt:string;operator:string;ipcStatus:string;result:string}; type Data={records:Rec[];counts:{pending:number;expiring:number;overdue:number;today:number}};
const nav=[["Tổng quan",LayoutDashboard],["Hóa chất",FlaskConical],["Pha chế & nhãn",Beaker],["Kế hoạch luân chuyển",CalendarDays],["Nhật ký vệ sinh",ClipboardCheck],["Phê duyệt IPC",ShieldCheck],["Tài liệu SOP",FileText]] as const;
const schedule=[{time:"08:00",area:"C1 · Phân xưởng BFS",task:"Tuần 1 & 3 · Vesphene 0,8%",status:"Đến hạn"},{time:"10:30",area:"C3 · Xưởng không vô trùng",task:"Chương trình 2 · Vesphene 0,8%",status:"Chờ thực hiện"},{time:"14:00",area:"S2 · Kho nguyên liệu",task:"Ethanol 70% · hàng ngày",status:"Chờ thực hiện"}];
const approved=["Ethanol · 70% · 7 ngày","LPH/Nước · 0,4% · 7 ngày","Vesphene II se/Nước · 0,8% · 7 ngày","H2O2 · 3% · 7 ngày","H2O2 · 5% · 7 ngày","QA 70 IPA · 70% · 7 ngày","Spor-Klenz RTU · dùng trực tiếp · 7 ngày","H2O2 · 35% · theo NSX","Cloramin B · 1% · theo NSX"];
export default function Home(){
 const [mobile,setMobile]=useState(false),[active,setActive]=useState("Tổng quan"),[open,setOpen]=useState(false),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[notice,setNotice]=useState("");
 const [data,setData]=useState<Data>({records:[],counts:{pending:0,expiring:0,overdue:0,today:0}}),[form,setForm]=useState({area:"",line:"",chemical:"",operator:"",result:"Đạt"});
 const load=async()=>{setLoading(true);try{const r=await fetch("/api/dashboard");if(r.ok)setData(await r.json())}catch{setNotice("Chưa thể kết nối dữ liệu. Vui lòng thử lại.")}finally{setLoading(false)}}; useEffect(()=>{void load()},[]);
 useEffect(()=>{const context=(document as unknown as {modelContext?:{registerTool:(tool:unknown,options?:unknown)=>void}}).modelContext;if(!context?.registerTool)return;const lifecycle=new AbortController();context.registerTool({name:"create_cleaning_record",title:"Ghi nhận vệ sinh",description:"Tạo một hồ sơ sử dụng hóa chất vệ sinh theo BM02 và chuyển sang trạng thái chờ IPC đối chiếu.",inputSchema:{type:"object",properties:{area:{type:"string"},line:{type:"string"},chemical:{type:"string"},operator:{type:"string"},result:{type:"string",enum:["Đạt","Không đạt"]}},required:["area","line","chemical","operator","result"],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute:async(input:unknown)=>{const r=await fetch("/api/records",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(input)});const out=await r.json();if(!r.ok)throw new Error(out.error||"Không thể lưu hồ sơ");await load();return{id:out.record.id,status:"Chờ đối chiếu"}}},{signal:lifecycle.signal});return()=>lifecycle.abort()},[]);
 const completion=useMemo(()=>Math.min(100,Math.round((data.counts.today/Math.max(3,data.counts.today+3))*100)),[data]);
 async function submit(e:React.FormEvent){e.preventDefault();setSaving(true);setNotice("");try{const r=await fetch("/api/records",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(form)}),o=await r.json();if(!r.ok)throw new Error(o.error||"Không thể lưu nhật ký");setOpen(false);setForm({area:"",line:"",chemical:"",operator:"",result:"Đạt"});setNotice("Đã ghi nhận. Nhật ký đang chờ IPC đối chiếu.");await load()}catch(e){setNotice(e instanceof Error?e.message:"Không thể lưu nhật ký")}finally{setSaving(false)}}
 return <main className="min-h-screen bg-[#f3f6f4] text-[#18231f]">
  <header className="sticky top-0 z-40 flex h-16 items-center border-b border-[#dce5df] bg-white/95 px-4 backdrop-blur lg:px-7"><button className="mr-3 lg:hidden" onClick={()=>setMobile(true)} aria-label="Mở menu"><Menu/></button><div className="flex items-center gap-3"><span className="grid h-9 w-9 place-items-center rounded-xl bg-[#0b6b4b] text-white"><Sparkles size={19}/></span><div><div className="font-semibold leading-tight">Vệ sinh nhà máy</div><div className="text-xs text-[#6d7c75]">SOP DB-QD-007 · Phiên bản 07</div></div></div><div className="ml-auto hidden w-[320px] items-center gap-2 rounded-xl border border-[#dce5df] bg-[#f7f9f8] px-3 py-2 text-sm text-[#718079] md:flex"><Search size={16}/> Tìm khu vực, hóa chất, hồ sơ...</div><div className="ml-4 grid h-9 w-9 place-items-center rounded-full bg-[#e0efe9] text-sm font-bold text-[#0b6b4b]">QA</div></header>
  <aside className={`fixed inset-y-0 left-0 z-50 w-[265px] border-r border-[#dce5df] bg-[#102d25] p-4 text-white transition-transform lg:top-16 lg:z-30 lg:translate-x-0 ${mobile?"translate-x-0":"-translate-x-full"}`}><div className="mb-4 flex items-center justify-between px-2 lg:hidden"><b>Điều hướng</b><button onClick={()=>setMobile(false)}><X/></button></div><nav className="space-y-1">{nav.map(([label,I])=><button key={label} onClick={()=>{setActive(label);setMobile(false)}} className={`flex w-full items-center gap-3 rounded-xl px-3 py-3 text-left text-sm ${active===label?"bg-[#1c6f56] text-white":"text-[#c8d8d2] hover:bg-white/10"}`}><I size={18}/>{label}{label==="Phê duyệt IPC"&&data.counts.pending>0&&<span className="ml-auto rounded-full bg-[#f4b740] px-2 py-0.5 text-[11px] font-bold text-[#322400]">{data.counts.pending}</span>}</button>)}</nav><div className="absolute bottom-5 left-4 right-4 rounded-xl border border-white/10 bg-white/5 p-3 text-xs leading-relaxed text-[#bbcec7]">Tuân thủ pha chế, sử dụng, luân chuyển và kiểm tra theo SOP. Không tự ý phối trộn hóa chất.</div></aside>
  <section className="px-4 py-6 lg:ml-[265px] lg:px-8 lg:py-8"><div className="mx-auto max-w-[1400px]">
   <div className="mb-7 flex flex-wrap items-end justify-between gap-4"><div><p className="mb-1 text-sm font-medium text-[#0b6b4b]">Thứ Bảy, 19 tháng 9, 2026</p><h1 className="text-2xl font-bold tracking-tight sm:text-3xl">Tổng quan kiểm soát vệ sinh</h1><p className="mt-1 text-sm text-[#64746d]">Theo dõi công việc, hạn dùng và hồ sơ cần IPC đối chiếu.</p></div>
   <Dialog open={open} onOpenChange={setOpen}><DialogTrigger render={<Button className="h-11 rounded-xl bg-[#0b6b4b] px-5 hover:bg-[#09583e]"/>}><Plus/> Ghi nhận vệ sinh</DialogTrigger><DialogContent className="sm:max-w-[560px]"><form onSubmit={submit}><DialogHeader><DialogTitle>Ghi nhận sử dụng hóa chất vệ sinh</DialogTitle><DialogDescription>Biểu mẫu điện tử dựa trên yêu cầu BM02. IPC sẽ đối chiếu sau khi lưu.</DialogDescription></DialogHeader><div className="grid gap-4 py-5 sm:grid-cols-2"><Field label="Khu vực *" value={form.area} change={v=>setForm({...form,area:v})} hint="Ví dụ: Phòng đóng gói"/><Field label="Line / cấp sạch *" value={form.line} change={v=>setForm({...form,line:v})} hint="Line 1 · Cấp D"/><div className="grid gap-2 sm:col-span-2"><Label>Hóa chất / mã mẻ *</Label><Input required value={form.chemical} onChange={e=>setForm({...form,chemical:e.target.value})} placeholder="Chọn theo PL01 sau khi cấu hình"/></div><Field label="Người thực hiện *" value={form.operator} change={v=>setForm({...form,operator:v})} hint="Họ và tên"/><div className="grid gap-2"><Label>Kết quả</Label><NativeSelect value={form.result} onChange={e=>setForm({...form,result:e.target.value})}><NativeSelectOption value="Đạt">Đạt</NativeSelectOption><NativeSelectOption value="Không đạt">Không đạt</NativeSelectOption></NativeSelect></div></div><div className="mb-4 rounded-xl bg-[#fff8e5] p-3 text-sm text-[#75520b]">Xác nhận đã kiểm tra nhãn, hạn dùng, bao bì kín và phiếu kiểm nghiệm còn hiệu lực.</div><DialogFooter><Button type="button" variant="outline" onClick={()=>setOpen(false)}>Hủy</Button><Button disabled={saving} className="bg-[#0b6b4b]">{saving?"Đang lưu...":"Lưu & chuyển IPC"}</Button></DialogFooter></form></DialogContent></Dialog></div>
   {notice&&<div className="mb-5 flex items-center gap-2 rounded-xl border border-[#b7d8ca] bg-[#edf8f3] px-4 py-3 text-sm text-[#0b6b4b]"><Check size={17}/>{notice}</div>}
   <div className="mb-6 grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{[["Công việc hôm nay",String(data.counts.today||3),"Theo kế hoạch PL03",CalendarDays,"green"],["Chờ IPC đối chiếu",String(data.counts.pending),"Hồ sơ BM02",ClipboardCheck,"amber"],["Sắp hết hạn",String(data.counts.expiring),"Trong 7 ngày",FlaskConical,"blue"],["Quá hạn",String(data.counts.overdue),"Cần xử lý ngay",AlertTriangle,"red"]].map(([t,v,s,I,c])=><article key={String(t)} className="metric-card"><div className={`metric-icon ${c}`}><I size={20}/></div><div><p className="text-sm text-[#687870]">{t}</p><p className="mt-1 text-2xl font-bold">{loading?"—":v}</p><p className="mt-1 text-xs text-[#7b8983]">{s}</p></div></article>)}</div>
   <div className="grid gap-6 xl:grid-cols-[1.65fr_1fr]"><article className="panel overflow-hidden"><Head title="Lịch vệ sinh hôm nay" sub="Công việc theo khu vực và chương trình luân chuyển"><Button variant="outline" size="sm" onClick={()=>void load()}><RefreshCw size={15}/> Làm mới</Button></Head><div className="divide-y divide-[#e7ede9]">{schedule.map((x,i)=><div key={x.time} className="grid grid-cols-[58px_1fr_auto] items-center gap-3 px-5 py-4 sm:grid-cols-[70px_1.2fr_1fr_auto]"><b className="text-sm text-[#31534a]">{x.time}</b><div><p className="font-medium">{x.area}</p><p className="text-xs text-[#7a8982] sm:hidden">{x.task}</p></div><p className="hidden text-sm text-[#5f6f68] sm:block">{x.task}<span className="block text-xs text-[#84918c]">Theo PL02</span></p><Badge className={i===0?"bg-[#fff0bf] text-[#785600]":"bg-[#eef2f0] text-[#56655e]"}>{x.status}</Badge></div>)}</div><div className="border-t border-[#e7ede9] px-5 py-4"><div className="mb-2 flex justify-between text-sm"><span>Tiến độ hôm nay</span><b>{completion}%</b></div><div className="h-2 rounded-full bg-[#e5ebe8]"><div className="h-full rounded-full bg-[#0b6b4b]" style={{width:`${completion}%`}}/></div></div></article>
   <article className="panel p-5"><div className="mb-5 flex justify-between"><div><h2 className="font-semibold">Sẵn sàng vận hành</h2><p className="text-sm text-[#73827b]">Cấu hình dữ liệu nền từ phụ lục</p></div><span className="h-fit rounded-full bg-[#fff2c9] px-2.5 py-1 text-xs font-semibold text-[#755508]">1/4 hoàn tất</span></div><div className="space-y-4">{[[true,"SOP DB-QD-007","Đã đối chiếu phiên bản 07"],[false,"Danh mục hóa chất PL01","Cần nhập loại, nồng độ, hạn dùng"],[false,"Ma trận khu vực PL02","Cần nhập hóa chất theo từng khu vực"],[false,"Chương trình luân chuyển PL03","Cần nhập lịch ngày/tuần/tháng"]].map(([d,t,s])=><div key={String(t)} className="flex gap-3"><span className={`mt-0.5 grid h-6 w-6 shrink-0 place-items-center rounded-full ${d?"bg-[#dcefe7] text-[#0b6b4b]":"border border-[#cad5cf] text-[#9aa7a1]"}`}>{d?<Check size={15}/>:<i className="h-1.5 w-1.5 rounded-full bg-current"/>}</span><div><p className="text-sm font-medium">{t}</p><p className="text-xs text-[#7b8983]">{s}</p></div></div>)}</div><Button variant="outline" className="mt-6 w-full border-[#b9d1c6] text-[#0b6b4b]">Cấu hình phụ lục</Button></article></div>
   <article className="panel mt-6 overflow-hidden"><Head title="Nhật ký gần đây" sub="Hồ sơ vệ sinh và trạng thái kiểm tra IPC"><Button variant="ghost" size="sm">Xem tất cả</Button></Head><div className="overflow-x-auto"><table className="w-full min-w-[760px] text-left text-sm"><thead className="bg-[#f6f8f7] text-xs uppercase tracking-wide text-[#718079]"><tr><th>Khu vực</th><th>Hóa chất / mẻ</th><th>Người thực hiện</th><th>Thời điểm</th><th>Kết quả</th><th>IPC</th></tr></thead><tbody>{data.records.length?data.records.map(r=><tr key={r.id}><td><b>{r.area}</b><span className="block text-xs text-[#7b8983]">{r.line}</span></td><td>{r.chemical}</td><td>{r.operator}</td><td>{new Date(r.cleanedAt).toLocaleString("vi-VN")}</td><td><Badge className={r.result==="Đạt"?"bg-[#e2f2eb] text-[#0b6b4b]":"bg-[#fee8e8] text-[#a72d2d]"}>{r.result}</Badge></td><td><Badge variant="outline">{r.ipcStatus}</Badge></td></tr>):<tr><td colSpan={6} className="py-10 text-center text-[#7b8983]">Chưa có hồ sơ. Chọn “Ghi nhận vệ sinh” để tạo nhật ký đầu tiên.</td></tr>}</tbody></table></div></article>
   <Tabs defaultValue="rules" className="mt-6"><TabsList><TabsTrigger value="rules">Điểm kiểm soát SOP</TabsTrigger><TabsTrigger value="scope">Phạm vi áp dụng</TabsTrigger></TabsList><TabsContent value="rules" className="panel mt-3 grid gap-3 p-5 md:grid-cols-3"><Rule title="Trước khi sử dụng" text="Kiểm tra đúng loại, còn hạn, bao bì kín và COA đạt."/><Rule title="Trong khi vệ sinh" text="Lau một chiều, sạch đến ít sạch, đủ thời gian tiếp xúc; không nhúng cây lau bẩn vào xô sạch."/><Rule title="Sau khi hoàn tất" text="Làm khô, xử lý tồn dư theo PL01 và ghi chép BM02 để IPC đối chiếu."/></TabsContent><TabsContent value="scope" className="panel mt-3 p-5 text-sm leading-7 text-[#52625b]">Áp dụng cho vệ sinh, khử trùng bề mặt thiết bị, nhà xưởng và sát khuẩn tay trong sản xuất hoặc bảo trì tại xưởng sản xuất, hệ thống phụ trợ, kho vận và khu vực quản lý chất lượng/phòng kiểm nghiệm.</TabsContent></Tabs>
   <article className="panel mt-6 p-5"><div className="mb-4 flex items-end justify-between gap-3"><div><h2 className="font-semibold">Danh mục hóa chất được phê duyệt</h2><p className="text-sm text-[#73827b]">PL01 · nồng độ sử dụng · hạn dùng sau mở nắp hoặc pha</p></div><Badge className="bg-[#e2f2eb] text-[#0b6b4b]">9 hóa chất</Badge></div><div className="grid gap-2 sm:grid-cols-2 lg:grid-cols-3">{approved.map(x=><div key={x} className="rounded-xl border border-[#e0e8e3] bg-[#f8faf9] px-3 py-2.5 text-sm">{x}</div>)}</div></article>
  </div></section>
 </main>}
function Field({label,value,change,hint}:{label:string;value:string;change:(v:string)=>void;hint:string}){return <div className="grid gap-2"><Label>{label}</Label><Input required value={value} onChange={e=>change(e.target.value)} placeholder={hint}/></div>}
function Head({title,sub,children}:{title:string;sub:string;children:React.ReactNode}){return <div className="panel-head"><div><h2>{title}</h2><p>{sub}</p></div>{children}</div>}
function Rule({title,text}:{title:string;text:string}){return <div className="rounded-xl border border-[#e0e8e3] bg-[#f8faf9] p-4"><h3 className="mb-1 font-semibold text-[#244c40]">{title}</h3><p className="text-sm leading-6 text-[#66766f]">{text}</p></div>}
