"use client";
import {useEffect,useMemo,useState} from "react";
import {AlertTriangle,Beaker,CalendarDays,Check,CheckCircle2,ChevronRight,ClipboardCheck,Clock3,FileText,FlaskConical,LayoutDashboard,Menu,Plus,RefreshCw,Search,ShieldCheck,Sparkles,X,XCircle} from "lucide-react";
import {areas,chemicals,preparationRule,recommendation,type Chemical} from "@/lib/sop";
import {Badge} from "@/components/ui/badge";import {Button} from "@/components/ui/button";import {Checkbox} from "@/components/ui/checkbox";import {Input} from "@/components/ui/input";import {Label} from "@/components/ui/label";import {NativeSelect,NativeSelectOption} from "@/components/ui/native-select";import {Tabs,TabsContent,TabsList,TabsTrigger} from "@/components/ui/tabs";
type Rec={id:number;area:string;line:string;chemical:string;cleanedAt:string;operator:string;ipcStatus:string;result:string};type Data={records:Rec[];counts:{pending:number;expiring:number;overdue:number;today:number}};
const nav=[["Tổng quan",LayoutDashboard],["Trợ lý vệ sinh",Sparkles],["Pha chế & nhãn",Beaker],["Nhật ký BM02",ClipboardCheck],["Phê duyệt IPC",ShieldCheck],["Tra cứu SOP",FileText]] as const;
export default function Home(){
 const [mobile,setMobile]=useState(false),[section,setSection]=useState("Trợ lý vệ sinh"),[data,setData]=useState<Data>({records:[],counts:{pending:0,expiring:0,overdue:0,today:0}}),[notice,setNotice]=useState("");
 const [areaCode,setAreaCode]=useState("C1"),[frequency,setFrequency]=useState<"routine"|"periodic">("routine"),[when,setWhen]=useState(new Date().toISOString().slice(0,16)),[operator,setOperator]=useState(""),[line,setLine]=useState("");
 const [checks,setChecks]=useState([false,false,false,false,false]),[saving,setSaving]=useState(false),[prepChem,setPrepChem]=useState("lph04"),[prepGrade,setPrepGrade]=useState("D"),[prepAt,setPrepAt]=useState(new Date().toISOString().slice(0,16));
 const load=async()=>{try{const r=await fetch("/api/dashboard");if(r.ok)setData(await r.json())}catch{setNotice("Không thể tải dữ liệu lúc này")}};useEffect(()=>{void load()},[]);
 const area=areas.find(a=>a.code===areaCode)!,rec=useMemo(()=>recommendation(area,new Date(when),frequency),[area,when,frequency]),chem=rec.chemical,rule=preparationRule(area.grade),allChecked=checks.every(Boolean),blocked=!chem||!allChecked||!operator.trim()||!line.trim();
 const selectedPrep=chemicals.find(c=>c.id===prepChem)!,prepRule=preparationRule(prepGrade),expiry=selectedPrep.expiryDays?new Date(new Date(prepAt).getTime()+selectedPrep.expiryDays*86400000):null;
 async function saveRecord(){if(blocked)return;setSaving(true);const payload={area:`${area.code} · ${area.name}`,line,chemical:`${chem!.name} ${chem!.concentration}`,operator,result:"Đạt"};try{const r=await fetch("/api/records",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(payload)}),o=await r.json();if(!r.ok)throw new Error(o.error);setNotice("Đã ghi nhận BM02 và chuyển IPC đối chiếu");setChecks([false,false,false,false,false]);setOperator("");await load()}catch(e){setNotice(e instanceof Error?e.message:"Không thể lưu")}finally{setSaving(false)}}
 async function review(id:number,status:string){const r=await fetch(`/api/records/${id}`,{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({status})});if(r.ok){setNotice(`Đã ${status.toLowerCase()} hồ sơ #${id}`);await load()}}
 return <main className="min-h-screen bg-[#f2f6f4] text-[#17231e]">
  <header className="sticky top-0 z-40 flex h-16 items-center border-b border-[#dbe5df] bg-white/95 px-4 backdrop-blur lg:px-7"><button className="mr-3 lg:hidden" onClick={()=>setMobile(true)}><Menu/></button><div className="flex items-center gap-3"><span className="grid h-9 w-9 place-items-center rounded-xl bg-[#0a6849] text-white"><Sparkles size={19}/></span><div><b>Vệ sinh nhà máy</b><div className="text-xs text-[#6d7c75]">DB-QD-007 · Phiên bản 07</div></div></div><div className="ml-auto hidden w-[310px] items-center gap-2 rounded-xl border bg-[#f7f9f8] px-3 py-2 text-sm text-[#718079] md:flex"><Search size={16}/>Tìm hóa chất, khu vực, hồ sơ</div><div className="ml-4 grid h-9 w-9 place-items-center rounded-full bg-[#e0efe9] text-sm font-bold text-[#0a6849]">QA</div></header>
  <aside className={`fixed inset-y-0 left-0 z-50 w-[265px] bg-[#102d25] p-4 text-white transition lg:top-16 lg:z-30 lg:translate-x-0 ${mobile?"translate-x-0":"-translate-x-full"}`}><div className="mb-4 flex justify-between px-2 lg:hidden"><b>Điều hướng</b><button onClick={()=>setMobile(false)}><X/></button></div><nav className="space-y-1">{nav.map(([n,I])=><button key={n} onClick={()=>{setSection(n);setMobile(false)}} className={`flex w-full items-center gap-3 rounded-xl px-3 py-3 text-left text-sm ${section===n?"bg-[#1b7056]":"text-[#c7d8d1] hover:bg-white/10"}`}><I size={18}/>{n}{n==="Phê duyệt IPC"&&data.counts.pending>0&&<span className="ml-auto rounded-full bg-[#f5bd48] px-2 text-xs font-bold text-[#3e2c00]">{data.counts.pending}</span>}</button>)}</nav><div className="absolute bottom-5 left-4 right-4 rounded-xl border border-white/10 bg-white/5 p-3 text-xs leading-5 text-[#c5d6d0]">Hệ thống kiểm tra chéo theo PL01–PL03. Không thay thế phê duyệt của QA/IPC.</div></aside>
  <section className="px-4 py-7 lg:ml-[265px] lg:px-8"><div className="mx-auto max-w-[1400px]">{notice&&<div className="mb-5 flex items-center gap-2 rounded-xl border border-[#b8d9ca] bg-[#ecf8f2] px-4 py-3 text-sm text-[#096748]"><CheckCircle2 size={18}/>{notice}</div>}
   {section==="Trợ lý vệ sinh"&&<Assistant areaCode={areaCode} setAreaCode={setAreaCode} frequency={frequency} setFrequency={setFrequency} when={when} setWhen={setWhen} operator={operator} setOperator={setOperator} line={line} setLine={setLine} checks={checks} setChecks={setChecks} area={area} chem={chem} reason={rec.reason} rule={rule} blocked={blocked} saving={saving} save={saveRecord}/>} 
   {section==="Tổng quan"&&<Dashboard data={data} go={()=>setSection("Trợ lý vệ sinh")}/>} 
   {section==="Pha chế & nhãn"&&<Preparation selected={selectedPrep} setChem={setPrepChem} grade={prepGrade} setGrade={setPrepGrade} preparedAt={prepAt} setPreparedAt={setPrepAt} rule={prepRule} expiry={expiry}/>} 
   {section==="Nhật ký BM02"&&<Records rows={data.records}/>} 
   {section==="Phê duyệt IPC"&&<Review rows={data.records.filter(r=>r.ipcStatus==="Chờ đối chiếu")} review={review}/>} 
   {section==="Tra cứu SOP"&&<Reference/>}
  </div></section>
 </main>
}
function Assistant(p:any){return <><Title eyebrow="HƯỚNG DẪN THEO NGỮ CẢNH" title="Trợ lý vệ sinh" sub="Chọn khu vực và thời điểm; hệ thống đối chiếu chương trình, hóa chất và điều kiện sử dụng."/><div className="grid gap-6 xl:grid-cols-[1.15fr_.85fr]"><article className="panel p-5 sm:p-6"><h2 className="section-title">1. Xác định công việc</h2><div className="mt-5 grid gap-4 sm:grid-cols-2"><Field label="Khu vực"><NativeSelect value={p.areaCode} onChange={(e:any)=>p.setAreaCode(e.target.value)}>{areas.map(a=><NativeSelectOption key={a.code} value={a.code}>{a.code} · {a.name} · {a.grade}</NativeSelectOption>)}</NativeSelect></Field><Field label="Thời điểm thực hiện"><Input type="datetime-local" value={p.when} onChange={(e:any)=>p.setWhen(e.target.value)}/></Field><Field label="Loại công việc"><NativeSelect value={p.frequency} onChange={(e:any)=>p.setFrequency(e.target.value)}><NativeSelectOption value="routine">Vệ sinh luân phiên tuần / hàng ngày</NativeSelectOption><NativeSelectOption value="periodic">Tổng vệ sinh định kỳ</NativeSelectOption></NativeSelect></Field><Field label="Line / vị trí cụ thể"><Input value={p.line} onChange={(e:any)=>p.setLine(e.target.value)} placeholder="Ví dụ: Line 1 · phòng 102"/></Field></div><h2 className="section-title mt-7">2. Kiểm tra trước sử dụng</h2><div className="mt-3 space-y-2">{["Nhãn đúng loại, đúng nồng độ và còn hạn dùng","Bao bì/chai chứa kín, nguyên vẹn","Có phiếu kiểm nghiệm đạt và còn hiệu lực","Dụng cụ đúng line, đúng cấp sạch; không dùng chéo","Đã được đào tạo; có đủ PPE"].map((x:string,i:number)=><label key={x} className="check-row"><Checkbox checked={p.checks[i]} onCheckedChange={(v:any)=>{const a=[...p.checks];a[i]=v===true;p.setChecks(a)}}/><span>{x}</span></label>)}</div><Field label="Người thực hiện"><Input value={p.operator} onChange={(e:any)=>p.setOperator(e.target.value)} placeholder="Họ và tên"/></Field><Button className="mt-5 h-11 w-full bg-[#0a6849]" disabled={p.blocked||p.saving} onClick={p.save}>{p.saving?"Đang lưu...":"Hoàn tất và chuyển IPC"}<ChevronRight/></Button>{p.blocked&&<p className="mt-2 text-center text-xs text-[#7a8982]">Hoàn thành đủ thông tin và 5 bước kiểm tra để tiếp tục.</p>}</article>
<div className="space-y-5"><article className={`panel overflow-hidden border-t-4 ${p.chem?"border-t-[#0a6849]":"border-t-[#c78b18]"}`}><div className="p-5"><div className="mb-3 flex items-center justify-between"><span className="text-xs font-bold tracking-wider text-[#6b7b74]">GỢI Ý TỪ PL02–PL03</span><Badge className={p.area.risk==="Cao"?"bg-[#fee8e8] text-[#9b2f2f]":"bg-[#e4f2eb] text-[#0a6849]"}>Rủi ro {p.area.risk.toLowerCase()}</Badge></div><h2 className="text-xl font-bold">{p.chem?`${p.chem.name} ${p.chem.concentration}`:"Cần QA xác nhận"}</h2><p className="mt-2 text-sm leading-6 text-[#5c6d65]">{p.reason}</p></div>{p.chem&&<div className="grid grid-cols-2 border-t bg-[#f8faf9] text-sm"><Info k="Chương trình" v={p.area.program==="Riêng"?"Tần suất riêng":`Chương trình ${p.area.program}`}/><Info k="Nhóm" v={p.chem.group}/><Info k="Hạn sau pha" v={p.chem.expiryDays?`${p.chem.expiryDays} ngày`:"Theo hạn NSX"}/><Info k="Giới hạn tồn dư" v={p.chem.residue}/></div>}</article>
<article className="panel p-5"><h3 className="font-semibold">Hướng dẫn pha chế theo cấp sạch {p.area.grade}</h3><div className="mt-4 space-y-3 text-sm"><Guide icon={<FlaskConical/>} k="Dung môi" v={p.rule.solvent}/><Guide icon={<Beaker/>} k="Khu vực pha" v={p.rule.area}/><Guide icon={<ShieldCheck/>} k="Dụng cụ" v={p.rule.utensil}/><Guide icon={<Sparkles/>} k="Xử lý khác" v={p.rule.treatment}/></div></article>
{p.chem?.needsEthanolWipe&&<div className="flex gap-3 rounded-xl border border-[#edcf88] bg-[#fff8e6] p-4 text-sm text-[#704f0d]"><AlertTriangle className="shrink-0" size={20}/><span>Hóa chất phenolic có giới hạn tồn dư 10 ppm. Sau vệ sinh phải lau lại bằng Ethanol 70%.</span></div>}<div className="rounded-xl border border-[#dbe5df] bg-white p-4 text-sm leading-6 text-[#52645b]"><b>Trình tự bắt buộc:</b> loại bỏ bụi/cặn bằng nước → làm sạch bằng hóa chất → làm khô. Lau một chiều, từ vùng sạch hơn đến ít sạch hơn và bảo đảm không bỏ sót.</div></div></div></>}
function Preparation(p:any){return <><Title eyebrow="BM01" title="Pha chế và tạo nhãn" sub="Tự động đối chiếu nồng độ, hạn dùng, dung môi và điều kiện xử lý dụng cụ."/><div className="grid gap-6 xl:grid-cols-[1fr_.8fr]"><article className="panel p-6"><div className="grid gap-4 sm:grid-cols-2"><Field label="Hóa chất"><NativeSelect value={p.selected.id} onChange={(e:any)=>p.setChem(e.target.value)}>{chemicals.map(c=><NativeSelectOption key={c.id} value={c.id}>{c.name} · {c.concentration}</NativeSelectOption>)}</NativeSelect></Field><Field label="Cấp sạch mục tiêu"><NativeSelect value={p.grade} onChange={(e:any)=>p.setGrade(e.target.value)}><NativeSelectOption value="D">Cấp D / CNC</NativeSelectOption><NativeSelectOption value="C">Cấp C</NativeSelectOption><NativeSelectOption value="A/B">Cấp A/B</NativeSelectOption></NativeSelect></Field><Field label="Ngày giờ pha"><Input type="datetime-local" value={p.preparedAt} onChange={(e:any)=>p.setPreparedAt(e.target.value)}/></Field><Field label="Người pha"><Input placeholder="Họ và tên"/></Field></div><div className="mt-6 grid gap-3 sm:grid-cols-2"><Guide icon={<FlaskConical/>} k="Nồng độ chuẩn" v={p.selected.concentration}/><Guide icon={<Beaker/>} k="Dung môi" v={p.rule.solvent}/><Guide icon={<ShieldCheck/>} k="Xử lý dụng cụ" v={p.rule.utensil}/><Guide icon={<Sparkles/>} k="Xử lý dung dịch" v={p.rule.treatment}/></div><div className="mt-5 rounded-xl bg-[#fff8e6] p-4 text-sm text-[#75520b]"><b>Kiểm tra chéo:</b> không được phối trộn với hóa chất khác. Chai/lọ phải được vệ sinh, kiểm tra nguyên vẹn trước khi chiết rót.</div></article><article className="label-preview"><div className="label-title">NHÃN HÓA CHẤT VỆ SINH SAU PHA CHẾ</div><LabelLine k="Tên hóa chất" v={p.selected.name}/><LabelLine k="Nồng độ pha" v={p.selected.concentration}/><LabelLine k="Ngày giờ pha" v={new Date(p.preparedAt).toLocaleString("vi-VN")}/><LabelLine k="Người pha" v="________________________"/><LabelLine k="Hạn sử dụng" v={p.expiry?p.expiry.toLocaleString("vi-VN"):"Theo hạn dùng của nhà sản xuất"}/><LabelLine k="Khu vực sử dụng" v={p.grade==="D"?"Grade D / CNC":"Grade A/B/C"}/><Button className="mt-5 w-full bg-[#0a6849]"><Plus/>Lưu mẻ pha & in nhãn</Button></article></div></>}
function Dashboard({data,go}:any){return <><Title eyebrow="HÔM NAY" title="Tổng quan kiểm soát" sub="Việc cần làm, hạn dùng và hồ sơ chờ đối chiếu."/><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{[["Đã ghi nhận",data.counts.today,CalendarDays,"green"],["Chờ IPC",data.counts.pending,ClipboardCheck,"amber"],["Sắp hết hạn",data.counts.expiring,FlaskConical,"blue"],["Quá hạn",data.counts.overdue,AlertTriangle,"red"]].map(([n,v,I,c]:any)=><article className="metric-card" key={n}><span className={`metric-icon ${c}`}><I/></span><div><p className="text-sm text-[#697971]">{n}</p><p className="text-2xl font-bold">{v}</p></div></article>)}</div><div className="mt-6 grid gap-6 lg:grid-cols-[1.4fr_.6fr]"><Records rows={data.records}/><article className="panel p-5"><h2 className="font-semibold">Bắt đầu đúng ngay từ đầu</h2><p className="mt-2 text-sm leading-6 text-[#66766e]">Trợ lý sẽ chọn chương trình và kiểm tra điều kiện trước khi lập hồ sơ BM02.</p><Button onClick={go} className="mt-5 w-full bg-[#0a6849]">Mở trợ lý vệ sinh<ChevronRight/></Button></article></div></>}
function Records({rows}:any){return <article className="panel overflow-hidden"><div className="panel-head"><div><h2>Nhật ký BM02 gần đây</h2><p>Thời điểm · chương trình · hóa chất · người dùng · xác nhận</p></div></div><div className="overflow-x-auto"><table className="w-full min-w-[700px] text-left text-sm"><thead><tr><th>Khu vực</th><th>Hóa chất</th><th>Người dùng</th><th>Thời điểm</th><th>IPC</th></tr></thead><tbody>{rows.length?rows.map((r:Rec)=><tr key={r.id}><td><b>{r.area}</b><small>{r.line}</small></td><td>{r.chemical}</td><td>{r.operator}</td><td>{new Date(r.cleanedAt).toLocaleString("vi-VN")}</td><td><Badge variant="outline">{r.ipcStatus}</Badge></td></tr>):<tr><td colSpan={5} className="py-10 text-center text-[#78877f]">Chưa có hồ sơ</td></tr>}</tbody></table></div></article>}
function Review({rows,review}:any){return <><Title eyebrow="KIỂM TRA CHÉO" title="Phê duyệt IPC" sub="Đối chiếu khu vực, hóa chất, thời điểm và người thực hiện trước khi xác nhận."/><div className="space-y-3">{rows.length?rows.map((r:Rec)=><article key={r.id} className="panel flex flex-wrap items-center gap-4 p-5"><div className="grid h-11 w-11 place-items-center rounded-xl bg-[#edf4f1] text-[#0a6849]"><ClipboardCheck/></div><div className="min-w-[220px] flex-1"><b>{r.area}</b><p className="text-sm text-[#687970]">{r.chemical} · {r.line} · {r.operator}</p><p className="text-xs text-[#85928c]">{new Date(r.cleanedAt).toLocaleString("vi-VN")}</p></div><Button variant="outline" onClick={()=>review(r.id,"Từ chối")}><XCircle/>Từ chối</Button><Button className="bg-[#0a6849]" onClick={()=>review(r.id,"Đã xác nhận")}><Check/>Xác nhận</Button></article>):<div className="panel py-16 text-center text-[#718179]"><CheckCircle2 className="mx-auto mb-3" size={34}/><b>Không có hồ sơ chờ IPC</b></div>}</div></>}
function Reference(){return <><Title eyebrow="PL01–PL03" title="Tra cứu nhanh SOP" sub="Danh mục hóa chất, ma trận khu vực và nguyên tắc vận hành."/><Tabs defaultValue="chem"><TabsList><TabsTrigger value="chem">9 hóa chất</TabsTrigger><TabsTrigger value="area">25 khu vực</TabsTrigger><TabsTrigger value="rules">Điểm kiểm soát</TabsTrigger></TabsList><TabsContent value="chem" className="panel mt-4 overflow-x-auto"><table className="w-full min-w-[760px] text-left text-sm"><thead><tr><th>Hóa chất</th><th>Nồng độ</th><th>Nhóm</th><th>Hạn dùng</th><th>Tồn dư</th></tr></thead><tbody>{chemicals.map(c=><tr key={c.id}><td><b>{c.name}</b><small>{c.purpose}</small></td><td>{c.concentration}</td><td>{c.group}</td><td>{c.expiryDays?`${c.expiryDays} ngày`:"Theo NSX"}</td><td>{c.residue}</td></tr>)}</tbody></table></TabsContent><TabsContent value="area" className="panel mt-4 overflow-x-auto"><table className="w-full min-w-[760px] text-left text-sm"><thead><tr><th>Mã</th><th>Khu vực</th><th>Cấp sạch</th><th>Rủi ro</th><th>Chương trình</th></tr></thead><tbody>{areas.map(a=><tr key={a.code}><td><b>{a.code}</b></td><td>{a.name}</td><td>{a.grade}</td><td>{a.risk}</td><td>{a.program==="NA"?"Chưa quy định":a.program==="Riêng"?a.rule:`Chương trình ${a.program}`}</td></tr>)}</tbody></table></TabsContent><TabsContent value="rules" className="panel mt-4 grid gap-3 p-5 md:grid-cols-3"><Rule t="Dụng cụ" x="Tách riêng theo line và cấp sạch. Dùng hệ thống 2–3 xô; không nhúng cây lau bẩn vào hóa chất sạch."/><Rule t="Thao tác" x="Lau một chiều, từ sạch hơn đến ít sạch hơn, phủ kín bề mặt và đủ thời gian tiếp xúc."/><Rule t="Luân chuyển" x="Luân chuyển nhóm có cơ chế khác nhau; điều chỉnh theo xu hướng vi sinh môi trường."/></TabsContent></Tabs></>}
function Title({eyebrow,title,sub}:any){return <div className="mb-7"><p className="text-xs font-bold tracking-[.14em] text-[#0a6849]">{eyebrow}</p><h1 className="mt-1 text-3xl font-bold tracking-tight">{title}</h1><p className="mt-1 text-sm text-[#66766e]">{sub}</p></div>};function Field({label,children}:any){return <label className="grid gap-2"><Label>{label}</Label>{children}</label>};function Info({k,v}:any){return <div className="border-b border-r p-3"><small>{k}</small><b className="block">{v}</b></div>};function Guide({icon,k,v}:any){return <div className="flex gap-3"><span className="text-[#0a6849]">{icon}</span><div><small>{k}</small><b className="block">{v}</b></div></div>};function LabelLine({k,v}:any){return <div className="border-b border-dashed border-[#809087] py-3"><small>{k}</small><b className="mt-1 block">{v}</b></div>};function Rule({t,x}:any){return <div className="rounded-xl border bg-[#f8faf9] p-4"><b>{t}</b><p className="mt-1 text-sm leading-6 text-[#66766e]">{x}</p></div>}
