create type public.app_role as enum ('factory_staff','ipc','admin');
create table public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  full_name text not null,
  role public.app_role not null default 'factory_staff',
  department_code text not null default 'UNASSIGNED',
  area_codes text[] not null default '{}',
  created_at timestamptz not null default now()
);
create table public.preparation_batches (
  id bigint generated by default as identity primary key,
  department_code text not null,
  chemical_id text not null,
  chemical_name text not null,
  concentration text not null,
  target_grade text not null,
  target_area_codes text[] not null,
  prepared_at timestamptz not null,
  prepared_by uuid not null references public.profiles(id),
  prepared_by_name text not null,
  expires_at timestamptz,
  manufacturer_expiry text,
  solvent text not null,
  treatment text not null,
  utensil_treatment text not null,
  container_integrity boolean not null default false,
  label_code text not null unique,
  status text not null default 'available' check(status in ('available','expired','quarantined')),
  created_at timestamptz not null default now()
);
create table public.cleaning_records (
  id bigint generated by default as identity primary key,
  department_code text not null,
  area_code text not null,
  area_name text not null,
  line text not null,
  program text not null,
  chemical_id text not null,
  chemical_name text not null,
  batch_id bigint references public.preparation_batches(id),
  purpose text not null,
  chemical_expiry timestamptz,
  used_at timestamptz not null,
  operator_id uuid not null references public.profiles(id),
  operator_name text not null,
  preuse_checks jsonb not null,
  result text not null check(result in ('pass','fail')),
  ipc_status text not null default 'pending' check(ipc_status in ('pending','approved','rejected')),
  checked_by uuid references public.profiles(id),
  checked_by_name text,
  checked_at timestamptz,
  rejection_reason text,
  created_at timestamptz not null default now()
);
create or replace function public.handle_new_user() returns trigger language plpgsql security definer set search_path=public as $$
begin
  insert into public.profiles(id,full_name,role,department_code,area_codes)
  values(new.id,coalesce(new.raw_user_meta_data->>'full_name',new.email),'factory_staff','UNASSIGNED','{}');
  return new;
end $$;
create trigger on_auth_user_created after insert on auth.users for each row execute procedure public.handle_new_user();
create index idx_profiles_role on public.profiles(role);
create index idx_batches_areas on public.preparation_batches using gin(target_area_codes);
create index idx_batches_expiry on public.preparation_batches(expires_at);
create index idx_records_area_used on public.cleaning_records(area_code,used_at desc);
create index idx_records_ipc on public.cleaning_records(ipc_status,created_at desc);
alter table public.profiles enable row level security;
alter table public.preparation_batches enable row level security;
alter table public.cleaning_records enable row level security;
create or replace function public.my_profile() returns public.profiles language sql stable security definer set search_path=public as $$ select * from public.profiles where id=auth.uid() $$;
create policy "read own profile" on public.profiles for select to authenticated using(id=auth.uid());
create policy "admin manages profiles" on public.profiles for all to authenticated using((select role from public.my_profile())='admin') with check((select role from public.my_profile())='admin');
create policy "read batches by department and area" on public.preparation_batches for select to authenticated using((select role from public.my_profile())='admin' or (department_code=(select department_code from public.my_profile()) and (((select role from public.my_profile())='ipc' and (cardinality((select area_codes from public.my_profile()))=0 or target_area_codes && (select area_codes from public.my_profile()))) or ((select role from public.my_profile())='factory_staff' and target_area_codes && (select area_codes from public.my_profile())))));
create policy "factory creates batches in scope" on public.preparation_batches for insert to authenticated with check(prepared_by=auth.uid() and ((select role from public.my_profile())='admin' or ((select role from public.my_profile())='factory_staff' and department_code=(select department_code from public.my_profile()) and target_area_codes <@ (select area_codes from public.my_profile()))));
create policy "read records by department and area" on public.cleaning_records for select to authenticated using((select role from public.my_profile())='admin' or (department_code=(select department_code from public.my_profile()) and (((select role from public.my_profile())='ipc' and (cardinality((select area_codes from public.my_profile()))=0 or area_code in (select unnest(area_codes) from public.my_profile()))) or ((select role from public.my_profile())='factory_staff' and area_code in (select unnest(area_codes) from public.my_profile())))));
create policy "factory creates records in scope" on public.cleaning_records for insert to authenticated with check(operator_id=auth.uid() and ((select role from public.my_profile())='admin' or ((select role from public.my_profile())='factory_staff' and department_code=(select department_code from public.my_profile()) and area_code in (select unnest(area_codes) from public.my_profile()))));
create policy "ipc reviews records in scope" on public.cleaning_records for update to authenticated using((select role from public.my_profile())='admin' or ((select role from public.my_profile())='ipc' and department_code=(select department_code from public.my_profile()) and (cardinality((select area_codes from public.my_profile()))=0 or area_code in (select unnest(area_codes) from public.my_profile())))) with check((select role from public.my_profile()) in ('ipc','admin'));
revoke all on public.profiles,public.preparation_batches,public.cleaning_records from anon;
grant select,update on public.profiles to authenticated;
grant select,insert on public.preparation_batches to authenticated;
grant select,insert,update on public.cleaning_records to authenticated;
grant usage,select on all sequences in schema public to authenticated;
